name: cwb-hub
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - pip
  
  # Core dependencies (via conda para melhor compatibilidade)
  - pydantic>=2.11.0
  - typing_extensions>=4.8.0
  
  # Pip dependencies
  - pip:
    - asyncio-mqtt>=0.16.1,<1.0.0
    - dataclasses-json>=0.6.3,<1.0.0
    - structlog>=23.2.0,<26.0.0
    - prometheus-client>=0.19.0,<1.0.0
    - pytest>=7.4.3,<9.0.0
    - pytest-asyncio>=0.21.1,<1.0.0
    - pytest-cov>=4.1.0,<6.0.0
    - black>=23.11.0,<25.0.0
    - flake8>=6.1.0,<8.0.0
    - mypy>=1.7.1,<2.0.0